workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 20
    environment:
      vars:
        JAVA_VERSION: 17
        ANDROID_SDK_VERSION: 34
    scripts:
      - name: Prepare Gradle Wrapper
        script: |
          chmod +x gradlew
      - name: Build Debug APK
        script: |
          ./gradlew clean
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - samer.cvm@gmail.com
